apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=          #minio as base64
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=     #minio123 as base64
