apiVersion: v1
kind: Service
metadata:
  name: "my-triton-inference-server-service"
  labels:
    app: "my-triton-inference-server"
spec:
  type: "LoadBalancer"
  ports:
    - port: 8000
      targetPort: http
      name: http-inference-server
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
  selector:
    app: "my-triton-inference-server"

