apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-tfserving
  name: my-tfserving-service
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: http-tf-serving
    port: 8500
    targetPort: 8500
  selector:
    app: my-tfserving
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-tfserving
  name: my-tfserving-deployment
spec:
  selector:
    matchLabels:
      app: my-tfserving
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: my-tfserving
        version: v1
    spec:
      containers:
      - args:
        - --port=9000
        - --rest_api_port=8500
        - --model_name=my-model
        - --model_base_path=s3://minio-service-kubeflow.apps:80/my-model-repository/my-model
#        - --monitoring_config_file=/var/config/monitoring_config.txt
        command:
        - /usr/bin/tensorflow_model_server
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: minio-s3-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: minio-s3-secret
        - name: AWS_REGION
          value: us-west-1
        - name: S3_USE_HTTPS
          value: "0"
        - name: S3_VERIFY_SSL
          value: "0"
        - name: S3_ENDPOINT
          value: minio-service:9000
        image: quay.io/ibm/kubeflow-tensorflow-serving-ppc64le:2.4.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 9000
        name: my-tfserving
        ports:
        - containerPort: 9000
        - containerPort: 8500
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/config/
          name: config-volume
      volumes:
      - configMap:
          name: workflow-controller-configmap
        name: config-volume
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
  name: my-tfserving-service
spec:
  host: my-tfserving-service
  subsets:
  - labels:
      version: v1
    name: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: my-tfserving-service
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - method:
        exact: POST
      uri:
        prefix: /tfserving/models/my-model
    rewrite:
      uri: /v1/models/my-model:predict
    route:
    - destination:
        host: my-tfserving-service
        port:
          number: 8500
        subset: v1
      weight: 100
